int orderNumber = 1;
double smartphonePrice = 305.99;
double laptopPrice = 570.95;
Console.WriteLine("Information for your 1st order");
Console.WriteLine("Enter your name: ");
string customerName = Console.ReadLine();
Console.WriteLine("Enter product name: ");
string productName = Console.ReadLine();
Console.WriteLine("Enter your address. Street: ");
string customerAddressStreet = Console.ReadLine();
Console.WriteLine("Building: ");
int customerAddressBuild = int.Parse(Console.ReadLine());
Console.WriteLine($"Order №{orderNumber}.");
Console.WriteLine($"Client: {customerName}.");
Console.WriteLine($"Product: {productName}, price: {smartphonePrice} EUR.");
Console.WriteLine($"Address: {customerAddressStreet}, {customerAddressBuild}.");

Console.WriteLine($"Information for your order №{++orderNumber}");
Console.WriteLine("Enter your name: ");
customerName = Console.ReadLine();
Console.WriteLine("Enter product name: ");
productName = Console.ReadLine();
Console.WriteLine("Enter your address. Street: ");
customerAddressStreet = Console.ReadLine();
Console.WriteLine("Building: ");
customerAddressBuild = int.Parse(Console.ReadLine());
Console.WriteLine($"Order №{orderNumber}.");
Console.WriteLine($"Client: {customerName}.");
Console.WriteLine($"Product: {productName}, price: {laptopPrice} EUR.");
Console.WriteLine($"Address: {customerAddressStreet}, {customerAddressBuild}.");

Console.WriteLine($"Information for your order №{++orderNumber}");
Console.WriteLine("Enter your name: ");
customerName = Console.ReadLine();
Console.WriteLine("Enter product name: ");
productName = Console.ReadLine();
Console.WriteLine("Enter product price: ");
double productPrice = double.Parse(Console.ReadLine());
Console.WriteLine("Enter your address. Street: ");
customerAddressStreet = Console.ReadLine();
Console.WriteLine("Building: ");
customerAddressBuild = int.Parse(Console.ReadLine());
Console.WriteLine($"Order №{orderNumber}.");
Console.WriteLine($"Client: {customerName}.");
Console.WriteLine($"Product: {productName}, price: {productPrice} EUR.");
Console.WriteLine($"Address: {customerAddressStreet}, {customerAddressBuild}.");